NexaMedicalDatabase = {}

local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_MEDICAL_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'medical.db' }) end

function NexaMedicalDatabase.Migrate()
    local db = coreDatabase()
    if not db or not db.RegisterMigration then return false, 'Core database unavailable.' end
    db.RegisterMigration({
        id = '160_medical_foundation',
        description = 'Create medical states injuries treatments deaths respawns and reports.',
        transaction = false,
        up = function()
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_states (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT UNIQUE NOT NULL, state VARCHAR(32) NOT NULL, pain INT NOT NULL DEFAULT 0, bleed_severity INT NOT NULL DEFAULT 0, is_unconscious TINYINT(1) NOT NULL DEFAULT 0, is_dead TINYINT(1) NOT NULL DEFAULT 0, last_injury_at TIMESTAMP NULL, metadata LONGTEXT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)]], {}, { category = 'medical.migration.states' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_injuries (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, injury_type VARCHAR(32) NOT NULL, severity INT NOT NULL, body_part VARCHAR(32) NULL, source_type VARCHAR(32) NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.injuries' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_treatments (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, medic_character_id BIGINT NULL, treatment_type VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, reason VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.treatments' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_reports (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, author_character_id BIGINT NULL, report_type VARCHAR(64) NOT NULL, summary TEXT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.reports' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_deaths (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, cause VARCHAR(64) NULL, declared_by BIGINT NULL, respawned_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.deaths' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_treatment_sessions (id INT AUTO_INCREMENT PRIMARY KEY, patient_character_id BIGINT NOT NULL, provider_character_id BIGINT NULL, treatment_key VARCHAR(64) NOT NULL, injury_id INT NULL, status VARCHAR(32) NOT NULL, started_at TIMESTAMP NULL, expected_end_at TIMESTAMP NULL, completed_at TIMESTAMP NULL, cancellation_reason VARCHAR(255) NULL, consumed_items_json LONGTEXT NULL, revision INT NOT NULL DEFAULT 0, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.sessions' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_medical_respawns (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, hospital_key VARCHAR(64) NOT NULL, actor_character_id BIGINT NULL, memory_loss_minutes INT NOT NULL DEFAULT 30, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'medical.migration.respawns' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS current_health INT NOT NULL DEFAULT 200]], {}, { category = 'medical.migration.states.health' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS max_health INT NOT NULL DEFAULT 200]], {}, { category = 'medical.migration.states.max_health' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS armor INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.states.armor' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS consciousness_state VARCHAR(32) NOT NULL DEFAULT 'conscious']], {}, { category = 'medical.migration.states.consciousness' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS death_state VARCHAR(32) NOT NULL DEFAULT 'alive']], {}, { category = 'medical.migration.states.death' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS mobility_state VARCHAR(32) NOT NULL DEFAULT 'normal']], {}, { category = 'medical.migration.states.mobility' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS incapacitated_at TIMESTAMP NULL]], {}, { category = 'medical.migration.states.incapacitated' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS declared_dead_at TIMESTAMP NULL]], {}, { category = 'medical.migration.states.declared_dead' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS respawn_available_at TIMESTAMP NULL]], {}, { category = 'medical.migration.states.respawn_available' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS treatment_lock VARCHAR(64) NULL]], {}, { category = 'medical.migration.states.treatment_lock' })
            db.Query([[ALTER TABLE nexa_medical_states ADD COLUMN IF NOT EXISTS revision INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.states.revision' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS body_region VARCHAR(32) NULL]], {}, { category = 'medical.migration.injuries.region' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS bleed_rate INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.injuries.bleed_rate' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS pain INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.injuries.pain' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS mobility_impact INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.injuries.mobility' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS consciousness_impact INT NOT NULL DEFAULT 0]], {}, { category = 'medical.migration.injuries.consciousness' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS treatable TINYINT(1) NOT NULL DEFAULT 1]], {}, { category = 'medical.migration.injuries.treatable' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS treated_state VARCHAR(32) NOT NULL DEFAULT 'untreated']], {}, { category = 'medical.migration.injuries.treated_state' })
            db.Query([[ALTER TABLE nexa_medical_injuries ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP NULL]], {}, { category = 'medical.migration.injuries.resolved_at' })
            db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_medical_state_character ON nexa_medical_states (character_id)]], {}, { category = 'medical.migration.index.state_character' })
            db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_medical_injury_character ON nexa_medical_injuries (character_id, status)]], {}, { category = 'medical.migration.index.injury_character' })
            return true
        end
    })
    return db.RunMigrations()
end

function NexaMedicalDatabase.EnsureState(characterId) return dbCall('Insert', 'INSERT INTO nexa_medical_states (character_id, state, metadata) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP', { characterId, NEXA_MEDICAL_STATE.healthy, encode({}) }, 'medical.state.ensure') end
function NexaMedicalDatabase.GetState(characterId) return dbCall('Single', 'SELECT * FROM nexa_medical_states WHERE character_id = ? LIMIT 1', { characterId }, 'medical.state.get') end
function NexaMedicalDatabase.UpdateState(characterId, s) return dbCall('Update', 'UPDATE nexa_medical_states SET state = ?, pain = ?, bleed_severity = ?, is_unconscious = ?, is_dead = ?, current_health = ?, max_health = ?, armor = ?, consciousness_state = ?, death_state = ?, mobility_state = ?, treatment_lock = ?, revision = revision + 1, last_injury_at = CURRENT_TIMESTAMP, metadata = ? WHERE character_id = ?', { s.state, s.pain, s.bleed_severity, s.is_unconscious and 1 or 0, s.is_dead and 1 or 0, s.current_health or 200, s.max_health or 200, s.armor or 0, s.consciousness_state or NEXA_CONSCIOUSNESS_STATE.conscious, s.death_state or NEXA_DEATH_STATE.alive, s.mobility_state or 'normal', s.treatment_lock, encode(s.metadata), characterId }, 'medical.state.update') end
function NexaMedicalDatabase.SetDeathState(characterId, state, metadata) return dbCall('Update', [[UPDATE nexa_medical_states SET death_state = ?, consciousness_state = ?, incapacitated_at = CASE WHEN ? IN ('incapacitated', 'critical') THEN COALESCE(incapacitated_at, CURRENT_TIMESTAMP) ELSE incapacitated_at END, declared_dead_at = CASE WHEN ? = 'dead' THEN COALESCE(declared_dead_at, CURRENT_TIMESTAMP) ELSE declared_dead_at END, revision = revision + 1, metadata = ? WHERE character_id = ?]], { state, state == NEXA_DEATH_STATE.alive and NEXA_CONSCIOUSNESS_STATE.conscious or NEXA_CONSCIOUSNESS_STATE.unconscious, state, state, encode(metadata), characterId }, 'medical.state.death') end
function NexaMedicalDatabase.InsertInjury(i) return dbCall('Insert', 'INSERT INTO nexa_medical_injuries (character_id, injury_type, severity, body_part, body_region, source_type, status, bleed_rate, pain, mobility_impact, consciousness_impact, treatable, treated_state, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', { i.character_id, i.injury_type, i.severity, i.body_part, i.body_region, i.source_type, i.status, i.bleed_rate or 0, i.pain or i.severity or 0, i.mobility_impact or 0, i.consciousness_impact or 0, i.treatable ~= false and 1 or 0, i.treated_state or 'untreated', encode(i.metadata) }, 'medical.injury.insert') end
function NexaMedicalDatabase.InsertTreatment(t) return dbCall('Insert', 'INSERT INTO nexa_medical_treatments (character_id, medic_character_id, treatment_type, status, reason, metadata) VALUES (?, ?, ?, ?, ?, ?)', { t.character_id, t.medic_character_id, t.treatment_type, t.status, t.reason, encode(t.metadata) }, 'medical.treatment.insert') end
function NexaMedicalDatabase.InsertTreatmentSession(t) return dbCall('Insert', 'INSERT INTO nexa_medical_treatment_sessions (patient_character_id, provider_character_id, treatment_key, injury_id, status, started_at, expected_end_at, consumed_items_json, metadata) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL ? SECOND), ?, ?)', { t.patient_character_id, t.provider_character_id, t.treatment_key, t.injury_id, t.status, math.floor((t.duration_ms or 0) / 1000), encode(t.consumed_items), encode(t.metadata) }, 'medical.session.insert') end
function NexaMedicalDatabase.GetTreatmentSession(id) return dbCall('Single', 'SELECT * FROM nexa_medical_treatment_sessions WHERE id = ? LIMIT 1', { id }, 'medical.session.get') end
function NexaMedicalDatabase.CompleteTreatmentSession(id, status, reason) return dbCall('Update', 'UPDATE nexa_medical_treatment_sessions SET status = ?, completed_at = CURRENT_TIMESTAMP, cancellation_reason = ?, revision = revision + 1 WHERE id = ? AND status IN ("pending", "active")', { status, reason, id }, 'medical.session.complete') end
function NexaMedicalDatabase.InsertReport(r) return dbCall('Insert', 'INSERT INTO nexa_medical_reports (character_id, author_character_id, report_type, summary, status, metadata) VALUES (?, ?, ?, ?, ?, ?)', { r.character_id, r.author_character_id, r.report_type, r.summary, r.status, encode(r.metadata) }, 'medical.report.insert') end
function NexaMedicalDatabase.ListReports(characterId) return dbCall('Query', 'SELECT * FROM nexa_medical_reports WHERE character_id = ? ORDER BY id DESC LIMIT 100', { characterId }, 'medical.report.list') end
function NexaMedicalDatabase.InsertDeath(d) return dbCall('Insert', 'INSERT INTO nexa_medical_deaths (character_id, cause, declared_by, metadata) VALUES (?, ?, ?, ?)', { d.character_id, d.cause, d.declared_by, encode(d.metadata) }, 'medical.death.insert') end
function NexaMedicalDatabase.InsertRespawn(r) return dbCall('Insert', 'INSERT INTO nexa_medical_respawns (character_id, hospital_key, actor_character_id, memory_loss_minutes, metadata) VALUES (?, ?, ?, ?, ?)', { r.character_id, r.hospital_key, r.actor_character_id, r.memory_loss_minutes or 30, encode(r.metadata) }, 'medical.respawn.insert') end
function NexaMedicalDatabase.GetSchema() return { migration = '160_medical_foundation', tables = { 'nexa_medical_states', 'nexa_medical_injuries', 'nexa_medical_treatments', 'nexa_medical_treatment_sessions', 'nexa_medical_reports', 'nexa_medical_deaths', 'nexa_medical_respawns' } } end
