local migrated = false

local function response(success, code, message, data, meta) return { ok = success == true, success = success == true, code = code or (success and 'OK' or NEXA_MEDICAL_ERRORS.invalidInput), message = message or '', data = data, meta = meta, error = success == true and nil or { code = code, message = message } } end
local function ok(data, message, meta) return response(true, 'OK', message or 'OK', data, meta) end
local function fail(code, message, meta) return response(false, code, message or code, nil, meta) end
local function encode(value) local good, encoded = pcall(json.encode, value or {}); return good and encoded or '{}' end
local function normalizeId(value) local id = tonumber(value); return id and id > 0 and id % 1 == 0 and math.floor(id) or nil end
local function clamp(value, min, max) value = tonumber(value) or 0; if value < min then return min end; if value > max then return max end; return math.floor(value) end
local function getCore() if GetResourceState('nexa-core') ~= 'started' then return nil end; local good, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return good and core or nil end
local function log(level, category, message, context) local core = getCore(); if core and core.Logger and core.Logger[level] then core.Logger[level](category, message, context); return end; print(('[%s] [%s] %s %s'):format(NEXA_MEDICAL.resourceName, level, message, encode(context))) end
local function emit(eventName, payload) local core = getCore(); if core and core.EventBus then core.EventBus.Emit(eventName, payload, { resource = NEXA_MEDICAL.resourceName }) end end
local injuryAliases = { blunt = 'blunt_trauma', cut = 'laceration', fall = 'blunt_trauma', vehicle = 'crush' }
local deathTransitions = { alive = { incapacitated = true, critical = true, dead = true }, incapacitated = { alive = true, critical = true, dead = true, respawned = true }, critical = { alive = true, dead = true, respawned = true }, dead = { respawned = true }, respawned = { alive = true } }
local function normalizeInjuryType(value) value = type(value) == 'string' and value or 'custom'; value = injuryAliases[value] or value; return NEXA_INJURY_TYPES[value] and value or nil end
local function normalizeBodyRegion(value) return NEXA_BODY_REGIONS[value] and value or 'torso' end
local function registerCallback(name, handler) if GetResourceState('nexa_api') == 'started' then exports.nexa_api:RegisterServerCallback(name, handler) end end
local function setDeathState(characterId, nextState, metadata)
    local current = NexaMedicalDatabase.GetState(characterId)
    local currentState = current and current.death_state or NEXA_DEATH_STATE.alive
    if currentState == nextState then return ok({ character_id = characterId, death_state = nextState }, 'Death state already set.') end
    if not (deathTransitions[currentState] and deathTransitions[currentState][nextState]) then return fail(NEXA_MEDICAL_ERRORS.invalidState, 'Medical death state transition is not allowed.', { from = currentState, to = nextState }) end
    NexaMedicalDatabase.SetDeathState(characterId, nextState, metadata or {})
    return ok({ character_id = characterId, death_state = nextState }, 'Death state updated.')
end

function GetMedicalState(characterId) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.EnsureState(characterId); local row, err = NexaMedicalDatabase.GetState(characterId); return err and fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical state could not be loaded.', err) or ok(row, 'Medical state loaded.') end
function ApplyInjury(characterId, injury) injury = type(injury) == 'table' and injury or {}; characterId = normalizeId(characterId); local injuryType = normalizeInjuryType(injury.injury_type); if not characterId or not injuryType then return fail(NEXA_MEDICAL_ERRORS.injuryInvalid, 'Injury is invalid.') end; local severity = clamp(injury.severity, 1, 100); local bleed = clamp(injury.bleed_severity or injury.bleed_rate or 0, 0, NexaMedicalConfig.maxBleedSeverity); local deathState = severity >= 95 and NEXA_DEATH_STATE.critical or (severity >= 80 and NEXA_DEATH_STATE.incapacitated or NEXA_DEATH_STATE.alive); NexaMedicalDatabase.EnsureState(characterId); NexaMedicalDatabase.InsertInjury({ character_id = characterId, injury_type = injuryType, severity = severity, body_part = injury.body_part, body_region = normalizeBodyRegion(injury.body_region or injury.body_part), source_type = injury.source_type, status = 'active', bleed_rate = bleed, pain = severity, mobility_impact = injury.mobility_impact, consciousness_impact = injury.consciousness_impact, treatable = injury.treatable, metadata = injury.metadata or {} }); NexaMedicalDatabase.UpdateState(characterId, { state = severity >= 80 and NEXA_MEDICAL_STATE.unconscious or (bleed > 0 and NEXA_MEDICAL_STATE.bleeding or NEXA_MEDICAL_STATE.injured), pain = severity, bleed_severity = bleed, is_unconscious = severity >= 80, is_dead = false, current_health = math.max(1, 200 - severity), consciousness_state = severity >= 80 and NEXA_CONSCIOUSNESS_STATE.unconscious or NEXA_CONSCIOUSNESS_STATE.conscious, death_state = deathState, mobility_state = severity >= 70 and 'limited' or 'normal', metadata = injury.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.injuryApplied, { character_id = characterId, severity = severity, injury_type = injuryType }); return ok({ character_id = characterId, severity = severity, injury_type = injuryType, death_state = deathState }, 'Injury applied.') end
function NormalizeDamageEvent(characterId, damage) damage = type(damage) == 'table' and damage or {}; local sourceType = damage.source_type or damage.weapon_type or 'unknown'; local injuryType = sourceType == 'firearm' and 'gunshot' or (sourceType == 'blade' and 'stab_wound' or (sourceType == 'vehicle' and 'crush' or 'blunt_trauma')); local severity = clamp(damage.severity or damage.damage or 10, 1, 100); emit(NEXA_MEDICAL_EVENTS.damageNormalized, { character_id = characterId, source_type = sourceType, severity = severity }); return ApplyInjury(characterId, { injury_type = injuryType, severity = severity, body_region = damage.body_region, source_type = sourceType, bleed_rate = damage.bleed_rate, metadata = { normalized = true, source = damage.source } }) end
function InspectPatient(characterId) local result = GetMedicalState(characterId); if not result.success then return result end; return ok({ state = result.data, restricted = true }, 'Patient inspection loaded.') end
function StabilizePatient(characterId, medicCharacterId, reason) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.recovering, pain = 40, bleed_severity = 0, is_unconscious = false, is_dead = false, current_health = 125, consciousness_state = NEXA_CONSCIOUSNESS_STATE.dazed, death_state = NEXA_DEATH_STATE.alive, mobility_state = 'limited', metadata = { stabilized = true } }); NexaMedicalDatabase.InsertTreatment({ character_id = characterId, medic_character_id = normalizeId(medicCharacterId), treatment_type = 'stabilize', status = 'completed', reason = reason, metadata = {} }); emit(NEXA_MEDICAL_EVENTS.patientStabilized, { character_id = characterId }); return ok({ character_id = characterId }, 'Patient stabilized.') end
function TreatPatient(characterId, treatment) treatment = type(treatment) == 'table' and treatment or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.InsertTreatment({ character_id = characterId, medic_character_id = normalizeId(treatment.medic_character_id), treatment_type = treatment.treatment_type or 'treatment', status = 'completed', reason = treatment.reason, metadata = treatment.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.patientTreated, { character_id = characterId, treatment_type = treatment.treatment_type }); return ok({ character_id = characterId }, 'Patient treated.') end
function StartTreatmentSession(characterId, providerCharacterId, treatment) treatment = type(treatment) == 'table' and treatment or {}; characterId = normalizeId(characterId); if not characterId or type(treatment.treatment_key) ~= 'string' then return fail(NEXA_MEDICAL_ERRORS.treatmentInvalid, 'Treatment session is invalid.') end; local id, err = NexaMedicalDatabase.InsertTreatmentSession({ patient_character_id = characterId, provider_character_id = normalizeId(providerCharacterId), treatment_key = treatment.treatment_key, injury_id = normalizeId(treatment.injury_id), status = NEXA_TREATMENT_STATUS.active, duration_ms = treatment.duration_ms or 5000, consumed_items = treatment.consumed_items or {}, metadata = treatment.metadata or {} }); if err then return fail(NEXA_MEDICAL_ERRORS.databaseError, 'Treatment session could not be started.', err) end; emit(NEXA_MEDICAL_EVENTS.treatmentStarted, { treatment_session_id = id, character_id = characterId }); return ok({ treatment_session_id = id }, 'Treatment session started.') end
function CompleteTreatmentSession(sessionId, payload) payload = type(payload) == 'table' and payload or {}; local session = NexaMedicalDatabase.GetTreatmentSession(normalizeId(sessionId)); if not session then return fail(NEXA_MEDICAL_ERRORS.treatmentInvalid, 'Treatment session not found.') end; if session.status == NEXA_TREATMENT_STATUS.completed then return fail(NEXA_MEDICAL_ERRORS.treatmentConflict, 'Treatment session is already completed.') end; NexaMedicalDatabase.CompleteTreatmentSession(session.id, NEXA_TREATMENT_STATUS.completed, nil); TreatPatient(session.patient_character_id, { medic_character_id = session.provider_character_id, treatment_type = session.treatment_key, metadata = payload.metadata }); emit(NEXA_MEDICAL_EVENTS.treatmentCompleted, { treatment_session_id = session.id }); return ok({ treatment_session_id = session.id }, 'Treatment session completed.') end
function CancelTreatmentSession(sessionId, reason) local session = NexaMedicalDatabase.GetTreatmentSession(normalizeId(sessionId)); if not session then return fail(NEXA_MEDICAL_ERRORS.treatmentInvalid, 'Treatment session not found.') end; NexaMedicalDatabase.CompleteTreatmentSession(session.id, NEXA_TREATMENT_STATUS.cancelled, reason); return ok({ treatment_session_id = session.id }, 'Treatment session cancelled.') end
function SetUnconscious(characterId, enabled, reason) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = enabled and NEXA_MEDICAL_STATE.unconscious or NEXA_MEDICAL_STATE.injured, pain = 80, bleed_severity = 0, is_unconscious = enabled == true, is_dead = false, current_health = enabled and 25 or 125, consciousness_state = enabled and NEXA_CONSCIOUSNESS_STATE.unconscious or NEXA_CONSCIOUSNESS_STATE.conscious, death_state = enabled and NEXA_DEATH_STATE.incapacitated or NEXA_DEATH_STATE.alive, mobility_state = enabled and 'downed' or 'normal', metadata = { reason = reason } }); return ok({ character_id = characterId, unconscious = enabled == true }, 'Unconscious state updated.') end
function SetDeathState(characterId, nextState, metadata) characterId = normalizeId(characterId); if not characterId or not NEXA_DEATH_STATE[nextState] then return fail(NEXA_MEDICAL_ERRORS.invalidState, 'Death state is invalid.') end; NexaMedicalDatabase.EnsureState(characterId); return setDeathState(characterId, nextState, metadata) end
function RecordDeath(characterId, payload) payload = type(payload) == 'table' and payload or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.dead, pain = 100, bleed_severity = 0, is_unconscious = true, is_dead = true, current_health = 0, consciousness_state = NEXA_CONSCIOUSNESS_STATE.unconscious, death_state = NEXA_DEATH_STATE.dead, mobility_state = 'downed', metadata = payload.metadata or {} }); local id = NexaMedicalDatabase.InsertDeath({ character_id = characterId, cause = payload.cause, declared_by = normalizeId(payload.declared_by), metadata = payload.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.patientDied, { character_id = characterId, death_id = id }); return ok({ character_id = characterId, death_id = id }, 'Death recorded.') end
function RespawnAtHospital(characterId, hospitalKey, actor) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; local hospital = hospitalKey or NexaMedicalConfig.defaultRespawnHospital; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.recovering, pain = 25, bleed_severity = 0, is_unconscious = false, is_dead = false, current_health = 150, consciousness_state = NEXA_CONSCIOUSNESS_STATE.dazed, death_state = NEXA_DEATH_STATE.respawned, mobility_state = 'limited', metadata = { hospital = hospital, memory_loss_minutes = 30 } }); NexaMedicalDatabase.InsertRespawn({ character_id = characterId, hospital_key = hospital, actor_character_id = type(actor) == 'table' and normalizeId(actor.character_id) or nil, memory_loss_minutes = 30, metadata = { actor = actor } }); emit(NEXA_MEDICAL_EVENTS.patientRespawned, { character_id = characterId, hospital = hospital }); return ok({ character_id = characterId, hospital = hospital, memory_loss_minutes = 30 }, 'Patient respawned at hospital.') end
function CreateMedicalReport(characterId, report) report = type(report) == 'table' and report or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; local id, err = NexaMedicalDatabase.InsertReport({ character_id = characterId, author_character_id = normalizeId(report.author_character_id), report_type = report.report_type or 'medical', summary = report.summary, status = report.status or 'open', metadata = report.metadata or {} }); if err then return fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical report could not be created.', err) end; emit(NEXA_MEDICAL_EVENTS.reportCreated, { report_id = id, character_id = characterId }); return ok({ report_id = id, character_id = characterId }, 'Medical report created.') end
function ListMedicalReports(characterId) local rows, err = NexaMedicalDatabase.ListReports(normalizeId(characterId)); return err and fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical reports could not be listed.', err) or ok(rows or {}, 'Medical reports listed.') end

local function registerCallbacks()
    registerCallback('nexa:medical:cb:getState', function(_, payload) return GetMedicalState(type(payload) == 'table' and payload.character_id or nil) end)
    registerCallback('nexa:medical:cb:inspectPatient', function(_, payload) return InspectPatient(type(payload) == 'table' and payload.character_id or nil) end)
    registerCallback('nexa:medical:cb:applyInjury', function(_, payload) payload = type(payload) == 'table' and payload or {}; return ApplyInjury(payload.character_id, payload.injury) end)
    registerCallback('nexa:medical:cb:startTreatment', function(_, payload) payload = type(payload) == 'table' and payload or {}; return StartTreatmentSession(payload.character_id, payload.provider_character_id, payload.treatment) end)
    registerCallback('nexa:medical:cb:completeTreatment', function(_, payload) payload = type(payload) == 'table' and payload or {}; return CompleteTreatmentSession(payload.treatment_session_id, payload) end)
    registerCallback('nexa:medical:cb:respawnAtHospital', function(_, payload) payload = type(payload) == 'table' and payload or {}; return RespawnAtHospital(payload.character_id, payload.hospital_key, payload.actor) end)
end

AddEventHandler('onResourceStart', function(resourceName) if resourceName ~= GetCurrentResourceName() then return end; if NexaMedicalConfig.autoMigrate then migrated = NexaMedicalDatabase.Migrate() == true end; registerCallbacks(); log('Info', 'medical.start', 'nexa_medical started.', { migrated = migrated }) end)
exports('GetMedicalState', GetMedicalState)
exports('ApplyInjury', ApplyInjury)
exports('NormalizeDamageEvent', NormalizeDamageEvent)
exports('InspectPatient', InspectPatient)
exports('StabilizePatient', StabilizePatient)
exports('TreatPatient', TreatPatient)
exports('StartTreatmentSession', StartTreatmentSession)
exports('CompleteTreatmentSession', CompleteTreatmentSession)
exports('CancelTreatmentSession', CancelTreatmentSession)
exports('SetUnconscious', SetUnconscious)
exports('SetDeathState', SetDeathState)
exports('RecordDeath', RecordDeath)
exports('RespawnAtHospital', RespawnAtHospital)
exports('CreateMedicalReport', CreateMedicalReport)
exports('ListMedicalReports', ListMedicalReports)
exports('getStatus', function() return { resourceName = NEXA_MEDICAL.resourceName, version = NEXA_MEDICAL.version, migrated = migrated } end)
exports('getSchema', NexaMedicalDatabase.GetSchema)
