local migrated = false

local function response(success, code, message, data, meta) return { ok = success == true, success = success == true, code = code or (success and 'OK' or NEXA_MEDICAL_ERRORS.invalidInput), message = message or '', data = data, meta = meta, error = success == true and nil or { code = code, message = message } } end
local function ok(data, message, meta) return response(true, 'OK', message or 'OK', data, meta) end
local function fail(code, message, meta) return response(false, code, message or code, nil, meta) end
local function encode(value) local good, encoded = pcall(json.encode, value or {}); return good and encoded or '{}' end
local function normalizeId(value) local id = tonumber(value); return id and id > 0 and id % 1 == 0 and math.floor(id) or nil end
local function clamp(value, min, max) value = tonumber(value) or 0; if value < min then return min end; if value > max then return max end; return math.floor(value) end
local function getCore() if GetResourceState('nexa-core') ~= 'started' then return nil end; local good, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return good and core or nil end
local function log(level, category, message, context) local core = getCore(); if core and core.Logger and core.Logger[level] then core.Logger[level](category, message, context); return end; print(('[%s] [%s] %s %s'):format(NEXA_MEDICAL.resourceName, level, message, encode(context))) end
local function emit(eventName, payload) local core = getCore(); if core and core.EventBus then core.EventBus.Emit(eventName, payload, { resource = NEXA_MEDICAL.resourceName }) end end

function GetMedicalState(characterId) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.EnsureState(characterId); local row, err = NexaMedicalDatabase.GetState(characterId); return err and fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical state could not be loaded.', err) or ok(row, 'Medical state loaded.') end
function ApplyInjury(characterId, injury) injury = type(injury) == 'table' and injury or {}; characterId = normalizeId(characterId); if not characterId or not NEXA_INJURY_TYPES[injury.injury_type or 'custom'] then return fail(NEXA_MEDICAL_ERRORS.injuryInvalid, 'Injury is invalid.') end; local severity = clamp(injury.severity, 1, 100); NexaMedicalDatabase.EnsureState(characterId); NexaMedicalDatabase.InsertInjury({ character_id = characterId, injury_type = injury.injury_type or 'custom', severity = severity, body_part = injury.body_part, source_type = injury.source_type, status = 'active', metadata = injury.metadata or {} }); NexaMedicalDatabase.UpdateState(characterId, { state = severity >= 80 and NEXA_MEDICAL_STATE.unconscious or NEXA_MEDICAL_STATE.injured, pain = severity, bleed_severity = clamp(injury.bleed_severity or 0, 0, NexaMedicalConfig.maxBleedSeverity), is_unconscious = severity >= 80, is_dead = false, metadata = injury.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.injuryApplied, { character_id = characterId, severity = severity }); return ok({ character_id = characterId, severity = severity }, 'Injury applied.') end
function StabilizePatient(characterId, medicCharacterId, reason) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.recovering, pain = 40, bleed_severity = 0, is_unconscious = false, is_dead = false, metadata = { stabilized = true } }); NexaMedicalDatabase.InsertTreatment({ character_id = characterId, medic_character_id = normalizeId(medicCharacterId), treatment_type = 'stabilize', status = 'completed', reason = reason, metadata = {} }); emit(NEXA_MEDICAL_EVENTS.patientStabilized, { character_id = characterId }); return ok({ character_id = characterId }, 'Patient stabilized.') end
function TreatPatient(characterId, treatment) treatment = type(treatment) == 'table' and treatment or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.InsertTreatment({ character_id = characterId, medic_character_id = normalizeId(treatment.medic_character_id), treatment_type = treatment.treatment_type or 'treatment', status = 'completed', reason = treatment.reason, metadata = treatment.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.patientTreated, { character_id = characterId, treatment_type = treatment.treatment_type }); return ok({ character_id = characterId }, 'Patient treated.') end
function SetUnconscious(characterId, enabled, reason) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = enabled and NEXA_MEDICAL_STATE.unconscious or NEXA_MEDICAL_STATE.injured, pain = 80, bleed_severity = 0, is_unconscious = enabled == true, is_dead = false, metadata = { reason = reason } }); return ok({ character_id = characterId, unconscious = enabled == true }, 'Unconscious state updated.') end
function RecordDeath(characterId, payload) payload = type(payload) == 'table' and payload or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.dead, pain = 100, bleed_severity = 0, is_unconscious = true, is_dead = true, metadata = payload.metadata or {} }); local id = NexaMedicalDatabase.InsertDeath({ character_id = characterId, cause = payload.cause, declared_by = normalizeId(payload.declared_by), metadata = payload.metadata or {} }); emit(NEXA_MEDICAL_EVENTS.patientDied, { character_id = characterId, death_id = id }); return ok({ character_id = characterId, death_id = id }, 'Death recorded.') end
function RespawnAtHospital(characterId, hospitalKey, actor) characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; NexaMedicalDatabase.UpdateState(characterId, { state = NEXA_MEDICAL_STATE.recovering, pain = 25, bleed_severity = 0, is_unconscious = false, is_dead = false, metadata = { hospital = hospitalKey or NexaMedicalConfig.defaultRespawnHospital } }); emit(NEXA_MEDICAL_EVENTS.patientRespawned, { character_id = characterId, hospital = hospitalKey or NexaMedicalConfig.defaultRespawnHospital }); return ok({ character_id = characterId, hospital = hospitalKey or NexaMedicalConfig.defaultRespawnHospital }, 'Patient respawned at hospital.') end
function CreateMedicalReport(characterId, report) report = type(report) == 'table' and report or {}; characterId = normalizeId(characterId); if not characterId then return fail(NEXA_MEDICAL_ERRORS.patientInvalid, 'Patient is invalid.') end; local id, err = NexaMedicalDatabase.InsertReport({ character_id = characterId, author_character_id = normalizeId(report.author_character_id), report_type = report.report_type or 'medical', summary = report.summary, status = report.status or 'open', metadata = report.metadata or {} }); if err then return fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical report could not be created.', err) end; emit(NEXA_MEDICAL_EVENTS.reportCreated, { report_id = id, character_id = characterId }); return ok({ report_id = id, character_id = characterId }, 'Medical report created.') end
function ListMedicalReports(characterId) local rows, err = NexaMedicalDatabase.ListReports(normalizeId(characterId)); return err and fail(NEXA_MEDICAL_ERRORS.databaseError, 'Medical reports could not be listed.', err) or ok(rows or {}, 'Medical reports listed.') end

AddEventHandler('onResourceStart', function(resourceName) if resourceName ~= GetCurrentResourceName() then return end; if NexaMedicalConfig.autoMigrate then migrated = NexaMedicalDatabase.Migrate() == true end; log('Info', 'medical.start', 'nexa_medical started.', { migrated = migrated }) end)
exports('GetMedicalState', GetMedicalState)
exports('ApplyInjury', ApplyInjury)
exports('StabilizePatient', StabilizePatient)
exports('TreatPatient', TreatPatient)
exports('SetUnconscious', SetUnconscious)
exports('RecordDeath', RecordDeath)
exports('RespawnAtHospital', RespawnAtHospital)
exports('CreateMedicalReport', CreateMedicalReport)
exports('ListMedicalReports', ListMedicalReports)
exports('getStatus', function() return { resourceName = NEXA_MEDICAL.resourceName, version = NEXA_MEDICAL.version, migrated = migrated } end)
exports('getSchema', NexaMedicalDatabase.GetSchema)
