NEXA_MEDICAL = { resourceName = 'nexa_medical', version = '0.2.0' }
NEXA_INJURY_TYPES = { blunt_trauma = 'blunt_trauma', laceration = 'laceration', gunshot = 'gunshot', stab_wound = 'stab_wound', burn = 'burn', fracture = 'fracture', sprain = 'sprain', crush = 'crush', concussion = 'concussion', internal_trauma = 'internal_trauma', overdose = 'overdose', custom = 'custom' }
NEXA_BODY_REGIONS = { head = 'head', neck = 'neck', torso = 'torso', left_arm = 'left_arm', right_arm = 'right_arm', left_leg = 'left_leg', right_leg = 'right_leg' }
NEXA_CONSCIOUSNESS_STATE = { conscious = 'conscious', dazed = 'dazed', unconscious = 'unconscious', sedated = 'sedated' }
NEXA_DEATH_STATE = { alive = 'alive', incapacitated = 'incapacitated', critical = 'critical', dead = 'dead', respawned = 'respawned' }
NEXA_TREATMENT_STATUS = { pending = 'pending', active = 'active', completed = 'completed', cancelled = 'cancelled', failed = 'failed' }
NEXA_MEDICAL_STATE = { healthy = 'healthy', injured = 'injured', bleeding = 'bleeding', unconscious = 'unconscious', dead = 'dead', recovering = 'recovering' }
NEXA_MEDICAL_EVENTS = { injuryApplied = 'nexa:internal:medical:injuryApplied', damageNormalized = 'nexa:internal:medical:damageNormalized', patientStabilized = 'nexa:internal:medical:patientStabilized', patientTreated = 'nexa:internal:medical:patientTreated', treatmentStarted = 'nexa:internal:medical:treatmentStarted', treatmentCompleted = 'nexa:internal:medical:treatmentCompleted', patientDied = 'nexa:internal:medical:patientDied', patientRespawned = 'nexa:internal:medical:patientRespawned', reportCreated = 'nexa:internal:medical:reportCreated' }
NEXA_MEDICAL_ERRORS = { stateNotFound = 'MEDICAL_STATE_NOT_FOUND', patientInvalid = 'MEDICAL_PATIENT_INVALID', injuryInvalid = 'MEDICAL_INJURY_INVALID', treatmentInvalid = 'MEDICAL_TREATMENT_INVALID', treatmentConflict = 'MEDICAL_TREATMENT_CONFLICT', reportNotFound = 'MEDICAL_REPORT_NOT_FOUND', reasonRequired = 'MEDICAL_REASON_REQUIRED', invalidState = 'MEDICAL_INVALID_STATE', invalidInput = 'MEDICAL_INVALID_INPUT', databaseError = 'MEDICAL_DATABASE_ERROR' }
