RegisterNUICallback('mdtClose', function(_, cb) close(); cb({ ok = true }) end)
RegisterNUICallback('mdtRefresh', function(_, cb) cb({ ok = true, data = refresh() }) end)
RegisterNUICallback('mdtSearchPerson', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:mdt:cb:searchPerson', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
RegisterNUICallback('mdtCreateReport', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:mdt:cb:createReport', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
