NexaDispatchDatabase = {}
local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_DISPATCH_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'dispatch.db' }) end
function NexaDispatchDatabase.Migrate() local db = coreDatabase(); if not db or not db.RegisterMigration then return false end; db.RegisterMigration({ id = '162_dispatch_foundation', description = 'Create dispatch calls units assignments and audit.', transaction = false, up = function() db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_call_types (id INT AUTO_INCREMENT PRIMARY KEY, call_type VARCHAR(64) UNIQUE NOT NULL, label VARCHAR(128) NOT NULL, default_priority INT NOT NULL DEFAULT 2, audience_json LONGTEXT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.types' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_calls (id INT AUTO_INCREMENT PRIMARY KEY, call_type VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, priority INT NOT NULL, caller_character_id BIGINT NULL, location_json LONGTEXT NULL, description TEXT NULL, dedupe_key VARCHAR(128) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.calls' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_units (id INT AUTO_INCREMENT PRIMARY KEY, unit_key VARCHAR(64) UNIQUE NOT NULL, label VARCHAR(128) NOT NULL, unit_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, gps_json LONGTEXT NULL, organization_id INT NULL, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.units' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_assignments (id INT AUTO_INCREMENT PRIMARY KEY, call_id INT NOT NULL, unit_key VARCHAR(64) NOT NULL, assigned_by BIGINT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.assignments' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_history (id INT AUTO_INCREMENT PRIMARY KEY, call_id INT NULL, unit_key VARCHAR(64) NULL, action VARCHAR(64) NOT NULL, actor_character_id BIGINT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.history' }); db.Query([[ALTER TABLE nexa_dispatch_calls ADD COLUMN IF NOT EXISTS dedupe_key VARCHAR(128) NULL]], {}, { category = 'dispatch.migration.calls.dedupe' }); db.Query([[ALTER TABLE nexa_dispatch_calls ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP]], {}, { category = 'dispatch.migration.calls.updated' }); db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_dispatch_calls_status ON nexa_dispatch_calls (status, priority)]], {}, { category = 'dispatch.migration.index.calls_status' }); return true end }); return db.RunMigrations() end
function NexaDispatchDatabase.UpsertCallType(t) return dbCall('Insert', 'INSERT INTO nexa_dispatch_call_types (call_type, label, default_priority, audience_json, enabled, metadata) VALUES (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE label = VALUES(label), default_priority = VALUES(default_priority), audience_json = VALUES(audience_json), enabled = VALUES(enabled), metadata = VALUES(metadata)', { t.call_type, t.label, t.default_priority, encode(t.audience), t.enabled and 1 or 0, encode(t.metadata) }, 'dispatch.type.upsert') end
function NexaDispatchDatabase.FindDedupeCall(key) return dbCall('Single', 'SELECT * FROM nexa_dispatch_calls WHERE dedupe_key = ? AND status NOT IN (?, ?, ?) ORDER BY id DESC LIMIT 1', { key, NEXA_DISPATCH_CALL_STATUS.resolved, NEXA_DISPATCH_CALL_STATUS.cancelled, NEXA_DISPATCH_CALL_STATUS.expired }, 'dispatch.call.dedupe') end
function NexaDispatchDatabase.InsertCall(c) return dbCall('Insert', 'INSERT INTO nexa_dispatch_calls (call_type, status, priority, caller_character_id, location_json, description, dedupe_key, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', { c.call_type, c.status, c.priority, c.caller_character_id, encode(c.location), c.description, c.dedupe_key, encode(c.metadata) }, 'dispatch.call.insert') end
function NexaDispatchDatabase.ListCalls(limit) return dbCall('Query', 'SELECT * FROM nexa_dispatch_calls ORDER BY id DESC LIMIT ?', { tonumber(limit) or 100 }, 'dispatch.call.list') end
function NexaDispatchDatabase.SetCallStatus(id, status) return dbCall('Update', 'UPDATE nexa_dispatch_calls SET status = ? WHERE id = ?', { status, id }, 'dispatch.call.status') end
function NexaDispatchDatabase.UpsertUnit(u) return dbCall('Insert', 'INSERT INTO nexa_dispatch_units (unit_key, label, unit_type, status, gps_json, organization_id, metadata) VALUES (?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE label = VALUES(label), unit_type = VALUES(unit_type), status = VALUES(status), gps_json = VALUES(gps_json), organization_id = VALUES(organization_id), metadata = VALUES(metadata)', { u.unit_key, u.label, u.unit_type, u.status, encode(u.gps), u.organization_id, encode(u.metadata) }, 'dispatch.unit.upsert') end
function NexaDispatchDatabase.GetUnit(key) return dbCall('Single', 'SELECT * FROM nexa_dispatch_units WHERE unit_key = ? LIMIT 1', { key }, 'dispatch.unit.get') end
function NexaDispatchDatabase.InsertAssignment(a) return dbCall('Insert', 'INSERT INTO nexa_dispatch_assignments (call_id, unit_key, assigned_by, status, metadata) VALUES (?, ?, ?, ?, ?)', { a.call_id, a.unit_key, a.assigned_by, a.status, encode(a.metadata) }, 'dispatch.assignment.insert') end
function NexaDispatchDatabase.InsertHistory(h) return dbCall('Insert', 'INSERT INTO nexa_dispatch_history (call_id, unit_key, action, actor_character_id, metadata) VALUES (?, ?, ?, ?, ?)', { h.call_id, h.unit_key, h.action, h.actor_character_id, encode(h.metadata) }, 'dispatch.history.insert') end
function NexaDispatchDatabase.GetSchema() return { migration = '162_dispatch_foundation', tables = { 'nexa_dispatch_call_types', 'nexa_dispatch_calls', 'nexa_dispatch_units', 'nexa_dispatch_assignments', 'nexa_dispatch_history' } } end
