NexaDispatchDatabase = {}
local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_DISPATCH_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'dispatch.db' }) end
function NexaDispatchDatabase.Migrate() local db = coreDatabase(); if not db or not db.RegisterMigration then return false end; db.RegisterMigration({ id = '162_dispatch_foundation', description = 'Create dispatch calls units assignments and audit.', transaction = false, up = function() db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_calls (id INT AUTO_INCREMENT PRIMARY KEY, call_type VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, priority INT NOT NULL, caller_character_id BIGINT NULL, location_json LONGTEXT NULL, description TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.calls' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_units (id INT AUTO_INCREMENT PRIMARY KEY, unit_key VARCHAR(64) UNIQUE NOT NULL, label VARCHAR(128) NOT NULL, unit_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, gps_json LONGTEXT NULL, organization_id INT NULL, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.units' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_dispatch_assignments (id INT AUTO_INCREMENT PRIMARY KEY, call_id INT NOT NULL, unit_key VARCHAR(64) NOT NULL, assigned_by BIGINT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'dispatch.migration.assignments' }); return true end }); return db.RunMigrations() end
function NexaDispatchDatabase.InsertCall(c) return dbCall('Insert', 'INSERT INTO nexa_dispatch_calls (call_type, status, priority, caller_character_id, location_json, description, metadata) VALUES (?, ?, ?, ?, ?, ?, ?)', { c.call_type, c.status, c.priority, c.caller_character_id, encode(c.location), c.description, encode(c.metadata) }, 'dispatch.call.insert') end
function NexaDispatchDatabase.ListCalls() return dbCall('Query', 'SELECT * FROM nexa_dispatch_calls ORDER BY id DESC LIMIT 500', {}, 'dispatch.call.list') end
function NexaDispatchDatabase.SetCallStatus(id, status) return dbCall('Update', 'UPDATE nexa_dispatch_calls SET status = ? WHERE id = ?', { status, id }, 'dispatch.call.status') end
function NexaDispatchDatabase.UpsertUnit(u) return dbCall('Insert', 'INSERT INTO nexa_dispatch_units (unit_key, label, unit_type, status, gps_json, organization_id, metadata) VALUES (?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE label = VALUES(label), unit_type = VALUES(unit_type), status = VALUES(status), gps_json = VALUES(gps_json), organization_id = VALUES(organization_id), metadata = VALUES(metadata)', { u.unit_key, u.label, u.unit_type, u.status, encode(u.gps), u.organization_id, encode(u.metadata) }, 'dispatch.unit.upsert') end
function NexaDispatchDatabase.GetUnit(key) return dbCall('Single', 'SELECT * FROM nexa_dispatch_units WHERE unit_key = ? LIMIT 1', { key }, 'dispatch.unit.get') end
function NexaDispatchDatabase.InsertAssignment(a) return dbCall('Insert', 'INSERT INTO nexa_dispatch_assignments (call_id, unit_key, assigned_by, status, metadata) VALUES (?, ?, ?, ?, ?)', { a.call_id, a.unit_key, a.assigned_by, a.status, encode(a.metadata) }, 'dispatch.assignment.insert') end
function NexaDispatchDatabase.GetSchema() return { migration = '162_dispatch_foundation', tables = { 'nexa_dispatch_calls', 'nexa_dispatch_units', 'nexa_dispatch_assignments' } } end
