local migrated = false
local adapters = {}
local function response(success, code, message, data, meta) return { ok = success == true, success = success == true, code = code or (success and 'OK' or NEXA_DISPATCH_ERRORS.invalidInput), message = message or '', data = data, meta = meta, error = success == true and nil or { code = code, message = message } } end
local function ok(data, message, meta) return response(true, 'OK', message or 'OK', data, meta) end
local function fail(code, message, meta) return response(false, code, message or code, nil, meta) end
local function encode(value) local good, encoded = pcall(json.encode, value or {}); return good and encoded or '{}' end
local function getCore() if GetResourceState('nexa-core') ~= 'started' then return nil end; local good, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return good and core or nil end
local function log(level, category, message, context) local core = getCore(); if core and core.Logger and core.Logger[level] then core.Logger[level](category, message, context); return end; print(('[%s] [%s] %s %s'):format(NEXA_DISPATCH.resourceName, level, message, encode(context))) end
local function emit(eventName, payload) local core = getCore(); if core and core.EventBus then core.EventBus.Emit(eventName, payload, { resource = NEXA_DISPATCH.resourceName }) end end
local function registerCallback(name, handler) if GetResourceState('nexa_api') == 'started' then exports.nexa_api:RegisterServerCallback(name, handler) end end
local function addHistory(callId, unitKey, action, actor, metadata) NexaDispatchDatabase.InsertHistory({ call_id = tonumber(callId), unit_key = unitKey, action = action, actor_character_id = type(actor) == 'table' and tonumber(actor.character_id) or nil, metadata = metadata or {} }) end
function RegisterCallType(definition) definition = type(definition) == 'table' and definition or {}; if type(definition.call_type) ~= 'string' or definition.call_type == '' then return fail(NEXA_DISPATCH_ERRORS.invalidInput, 'Dispatch call type is invalid.') end; local id, err = NexaDispatchDatabase.UpsertCallType({ call_type = definition.call_type, label = definition.label or definition.call_type, default_priority = tonumber(definition.default_priority) or NexaDispatchConfig.defaultCallPriority, audience = definition.audience or {}, enabled = definition.enabled ~= false, metadata = definition.metadata or {} }); if err then return fail(NEXA_DISPATCH_ERRORS.databaseError, 'Dispatch call type could not be registered.', err) end; emit(NEXA_DISPATCH_EVENTS.callTypeRegistered, { call_type = definition.call_type }); return ok({ call_type_id = id, call_type = definition.call_type }, 'Dispatch call type registered.') end
function CreateDispatchCall(payload) payload = type(payload) == 'table' and payload or {}; if payload.dedupe_key then local existing = NexaDispatchDatabase.FindDedupeCall(payload.dedupe_key); if existing then return ok({ call_id = existing.id, deduped = true }, 'Dispatch call already exists.') end end; local id, err = NexaDispatchDatabase.InsertCall({ call_type = payload.call_type or 'emergency', status = NEXA_DISPATCH_CALL_STATUS.open, priority = tonumber(payload.priority) or NexaDispatchConfig.defaultCallPriority, caller_character_id = tonumber(payload.caller_character_id), location = payload.location or {}, description = payload.description, dedupe_key = payload.dedupe_key, metadata = payload.metadata or {} }); if err then return fail(NEXA_DISPATCH_ERRORS.databaseError, 'Dispatch call could not be created.', err) end; addHistory(id, nil, 'created', payload.actor, { call_type = payload.call_type }); emit(NEXA_DISPATCH_EVENTS.callCreated, { call_id = id }); return ok({ call_id = id }, 'Dispatch call created.') end
function ListDispatchCalls(filter) filter = type(filter) == 'table' and filter or {}; local rows, err = NexaDispatchDatabase.ListCalls(filter.limit or NexaDispatchConfig.maxListLimit); return err and fail(NEXA_DISPATCH_ERRORS.databaseError, 'Dispatch calls could not be listed.', err) or ok(rows or {}, 'Dispatch calls listed.') end
function AssignDispatchUnit(callId, unitKey, actor) local id, err = NexaDispatchDatabase.InsertAssignment({ call_id = tonumber(callId), unit_key = unitKey, assigned_by = type(actor) == 'table' and tonumber(actor.character_id) or nil, status = 'assigned', metadata = {} }); if err then return fail(NEXA_DISPATCH_ERRORS.databaseError, 'Dispatch unit could not be assigned.', err) end; NexaDispatchDatabase.SetCallStatus(tonumber(callId), NEXA_DISPATCH_CALL_STATUS.assigned); addHistory(callId, unitKey, 'assigned', actor, {}); emit(NEXA_DISPATCH_EVENTS.unitAssigned, { assignment_id = id, call_id = callId, unit_key = unitKey }); return ok({ assignment_id = id }, 'Dispatch unit assigned.') end
function UpdateDispatchStatus(callId, status, actor) if not NEXA_DISPATCH_CALL_STATUS[status] then return fail(NEXA_DISPATCH_ERRORS.statusInvalid, 'Dispatch status is invalid.') end; NexaDispatchDatabase.SetCallStatus(tonumber(callId), status); addHistory(callId, nil, 'status:' .. status, actor, {}); emit(NEXA_DISPATCH_EVENTS.callStatusChanged, { call_id = callId, status = status }); return ok({ call_id = callId, status = status }, 'Dispatch status updated.') end
function SetUnitStatus(unitKey, status, payload) payload = type(payload) == 'table' and payload or {}; if not NEXA_DISPATCH_UNIT_STATUS[status] then return fail(NEXA_DISPATCH_ERRORS.statusInvalid, 'Unit status is invalid.') end; NexaDispatchDatabase.UpsertUnit({ unit_key = unitKey, label = payload.label or unitKey, unit_type = payload.unit_type or 'police', status = status or NexaDispatchConfig.defaultUnitStatus, gps = payload.gps or {}, organization_id = tonumber(payload.organization_id), metadata = payload.metadata or {} }); addHistory(payload.call_id, unitKey, 'unit_status:' .. status, payload.actor, { gps = payload.gps }); emit(NEXA_DISPATCH_EVENTS.unitStatusChanged, { unit_key = unitKey, status = status }); return ok({ unit_key = unitKey, status = status }, 'Unit status updated.') end
function CreatePanic(unitKey, payload) payload = type(payload) == 'table' and payload or {}; SetUnitStatus(unitKey, NEXA_DISPATCH_UNIT_STATUS.panic, payload); local call = CreateDispatchCall({ call_type = 'panic', priority = 1, location = payload.location, description = payload.description or 'Panic alarm', dedupe_key = 'panic:' .. tostring(unitKey), metadata = { unit_key = unitKey }, actor = payload.actor }); emit(NEXA_DISPATCH_EVENTS.panicCreated, { unit_key = unitKey, call_id = call.data and call.data.call_id or nil }); return call end
function GetUnitStatus(unitKey) local row, err = NexaDispatchDatabase.GetUnit(unitKey); return err and fail(NEXA_DISPATCH_ERRORS.databaseError, 'Unit could not be loaded.', err) or (row and ok(row, 'Unit loaded.') or fail(NEXA_DISPATCH_ERRORS.unitNotFound, 'Unit not found.')) end
function RegisterDispatchAdapter(name, adapter) if type(name) ~= 'string' or type(adapter) ~= 'table' then return false end; adapters[name] = adapter; return true end
local function registerCallbacks()
    registerCallback('nexa:dispatch:cb:registerCallType', function(_, payload) return RegisterCallType(payload) end)
    registerCallback('nexa:dispatch:cb:createCall', function(_, payload) return CreateDispatchCall(payload) end)
    registerCallback('nexa:dispatch:cb:listCalls', function(_, payload) return ListDispatchCalls(payload) end)
    registerCallback('nexa:dispatch:cb:assignUnit', function(_, payload) payload = type(payload) == 'table' and payload or {}; return AssignDispatchUnit(payload.call_id, payload.unit_key, payload.actor) end)
    registerCallback('nexa:dispatch:cb:updateStatus', function(_, payload) payload = type(payload) == 'table' and payload or {}; return UpdateDispatchStatus(payload.call_id, payload.status, payload.actor) end)
    registerCallback('nexa:dispatch:cb:setUnitStatus', function(_, payload) payload = type(payload) == 'table' and payload or {}; return SetUnitStatus(payload.unit_key, payload.status, payload) end)
    registerCallback('nexa:dispatch:cb:panic', function(_, payload) payload = type(payload) == 'table' and payload or {}; return CreatePanic(payload.unit_key, payload) end)
end
AddEventHandler('onResourceStart', function(resourceName) if resourceName ~= GetCurrentResourceName() then return end; if NexaDispatchConfig.autoMigrate then migrated = NexaDispatchDatabase.Migrate() == true end; registerCallbacks(); log('Info', 'dispatch.start', 'nexa_dispatch started.', { migrated = migrated }) end)
exports('RegisterCallType', RegisterCallType)
exports('CreateDispatchCall', CreateDispatchCall)
exports('ListDispatchCalls', ListDispatchCalls)
exports('AssignDispatchUnit', AssignDispatchUnit)
exports('UpdateDispatchStatus', UpdateDispatchStatus)
exports('SetUnitStatus', SetUnitStatus)
exports('CreatePanic', CreatePanic)
exports('GetUnitStatus', GetUnitStatus)
exports('RegisterDispatchAdapter', RegisterDispatchAdapter)
exports('getStatus', function() return { resourceName = NEXA_DISPATCH.resourceName, version = NEXA_DISPATCH.version, migrated = migrated, adapters = adapters } end)
exports('getSchema', NexaDispatchDatabase.GetSchema)
