NexaLicensesDatabase = {}
local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_LICENSE_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'licenses.db' }) end
function NexaLicensesDatabase.Migrate() local db = coreDatabase(); if not db or not db.RegisterMigration then return false end; db.RegisterMigration({ id = '163_licenses_foundation', description = 'Create license types records and history.', transaction = false, up = function() db.Query([[CREATE TABLE IF NOT EXISTS nexa_license_types (id INT AUTO_INCREMENT PRIMARY KEY, license_key VARCHAR(64) UNIQUE NOT NULL, label VARCHAR(128) NOT NULL, license_type VARCHAR(32) NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1, metadata LONGTEXT NULL)]], {}, { category = 'licenses.migration.types' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_licenses (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, license_key VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, issued_by BIGINT NULL, issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP NULL, revoked_at TIMESTAMP NULL, suspended_at TIMESTAMP NULL, metadata LONGTEXT NULL)]], {}, { category = 'licenses.migration.records' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_license_history (id INT AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, license_key VARCHAR(64) NOT NULL, action VARCHAR(32) NOT NULL, actor_character_id BIGINT NULL, reason VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'licenses.migration.history' }); db.Query([[ALTER TABLE nexa_licenses ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP NULL]], {}, { category = 'licenses.migration.records.expires' }); db.Query([[ALTER TABLE nexa_licenses ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP NULL]], {}, { category = 'licenses.migration.records.suspended' }); db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_licenses_character ON nexa_licenses (character_id, license_key, status)]], {}, { category = 'licenses.migration.index.character' }); return true end }); return db.RunMigrations() end
function NexaLicensesDatabase.UpsertType(t) return dbCall('Insert', 'INSERT INTO nexa_license_types (license_key, label, license_type, enabled, metadata) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE label = VALUES(label), license_type = VALUES(license_type), enabled = VALUES(enabled), metadata = VALUES(metadata)', { t.license_key, t.label, t.license_type, t.enabled and 1 or 0, encode(t.metadata) }, 'licenses.type.upsert') end
function NexaLicensesDatabase.ListTypes() return dbCall('Query', 'SELECT * FROM nexa_license_types ORDER BY license_key ASC', {}, 'licenses.type.list') end
function NexaLicensesDatabase.InsertLicense(l) return dbCall('Insert', 'INSERT INTO nexa_licenses (character_id, license_key, status, issued_by, metadata) VALUES (?, ?, ?, ?, ?)', { l.character_id, l.license_key, l.status, l.issued_by, encode(l.metadata) }, 'licenses.record.insert') end
function NexaLicensesDatabase.GetLicense(characterId, licenseKey) return dbCall('Single', 'SELECT * FROM nexa_licenses WHERE character_id = ? AND license_key = ? AND revoked_at IS NULL ORDER BY id DESC LIMIT 1', { characterId, licenseKey }, 'licenses.record.get') end
function NexaLicensesDatabase.SetLicenseStatus(characterId, licenseKey, status) return dbCall('Update', 'UPDATE nexa_licenses SET status = ?, suspended_at = CASE WHEN ? = ? THEN CURRENT_TIMESTAMP ELSE suspended_at END, revoked_at = CASE WHEN ? = ? THEN CURRENT_TIMESTAMP ELSE revoked_at END WHERE character_id = ? AND license_key = ? AND revoked_at IS NULL', { status, status, NEXA_LICENSE_STATUS.suspended, status, NEXA_LICENSE_STATUS.revoked, characterId, licenseKey }, 'licenses.record.status') end
function NexaLicensesDatabase.RevokeLicense(characterId, licenseKey) return dbCall('Update', 'UPDATE nexa_licenses SET status = ?, revoked_at = CURRENT_TIMESTAMP WHERE character_id = ? AND license_key = ? AND revoked_at IS NULL', { 'revoked', characterId, licenseKey }, 'licenses.record.revoke') end
function NexaLicensesDatabase.InsertHistory(h) return dbCall('Insert', 'INSERT INTO nexa_license_history (character_id, license_key, action, actor_character_id, reason, metadata) VALUES (?, ?, ?, ?, ?, ?)', { h.character_id, h.license_key, h.action, h.actor_character_id, h.reason, encode(h.metadata) }, 'licenses.history.insert') end
function NexaLicensesDatabase.GetHistory(characterId) return dbCall('Query', 'SELECT * FROM nexa_license_history WHERE character_id = ? ORDER BY id DESC LIMIT 100', { characterId }, 'licenses.history.list') end
function NexaLicensesDatabase.GetSchema() return { migration = '163_licenses_foundation', tables = { 'nexa_license_types', 'nexa_licenses', 'nexa_license_history' } } end
