RegisterNUICallback('bankingClose', function(_, cb) close(); cb({ ok = true }) end)
RegisterNUICallback('bankingRefresh', function(_, cb) cb({ ok = true, data = refresh() }) end)
RegisterNUICallback('bankingTransfer', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:banking:cb:requestTransfer', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
RegisterNUICallback('bankingPayInvoice', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:banking:cb:payInvoice', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
