RegisterNUICallback('dispatchClose', function(_, cb) close(); cb({ ok = true }) end)
RegisterNUICallback('dispatchRefresh', function(_, cb) cb({ ok = true, data = refresh() }) end)
RegisterNUICallback('dispatchAssign', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:dispatch:cb:assignUnit', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
RegisterNUICallback('dispatchStatus', function(data, cb)
    local waiter = promise.new()
    exports.nexa_api:TriggerServerCallback('nexa:dispatch:cb:updateStatus', data or {}, function(response) waiter:resolve(response) end, 5000)
    cb(Citizen.Await(waiter) or { ok = false })
end)
