$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$securityDir = Join-Path $root 'docs\security'
$dataDir = Join-Path $securityDir '.audit-data'
New-Item -ItemType Directory -Force -Path $securityDir | Out-Null

function Read-AuditJson {
    param([string]$Name)
    $path = Join-Path $dataDir "$Name.json"
    if (-not (Test-Path -LiteralPath $path)) {
        return [pscustomobject]@{ findings = @(); skipped = @() }
    }
    return Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
}

function Get-RepoFiles {
    $files = & rg --files --hidden -g '!.git/**' -g '!**/node_modules/**' -g '!**/dist/**' -g '!**/build/**' -g '!**/.next/**' -g '!**/coverage/**' -g '!**/vendor/**' -g '!.agents/**' -g '!.codex/**'
    return @($files | Where-Object { $_ -and (Test-Path -LiteralPath (Join-Path $root $_)) })
}

function Escape-Cell {
    param($Value)
    return (Stringify $Value).Replace('|', '\|').Replace("`r", ' ').Replace("`n", ' ')
}

function Stringify {
    param($Value)
    if ($null -eq $Value) { return '' }
    return [string]$Value
}

function Finding-Table {
    param($Findings, [int]$Limit = 80)
    $rows = @('| Severity | File | Line | Rule | Finding | Evidence |', '| --- | --- | ---: | --- | --- | --- |')
    foreach ($finding in @($Findings | Select-Object -First $Limit)) {
        $rows += '| {0} | {1} | {2} | {3} | {4} | {5} |' -f (Escape-Cell $finding.Severity), (Escape-Cell $finding.Path), (Escape-Cell $finding.Line), (Escape-Cell $finding.Rule), (Escape-Cell $finding.Message), (Escape-Cell $finding.Evidence)
    }
    if (@($Findings).Count -gt $Limit) {
        $rows += ''
        $rows += "_Table truncated to $Limit rows. Full finding count: $(@($Findings).Count)._"
    }
    return ($rows -join "`n")
}

function Write-Report {
    param(
        [string]$Path,
        [string]$Title,
        [string]$Scope,
        $Findings,
        [string[]]$Extra = @()
    )
    $counts = @($Findings | Group-Object Severity | ForEach-Object { "$($_.Name)=$($_.Count)" }) -join ', '
    if ($counts -eq '') { $counts = 'none' }
    $content = @(
        "# $Title",
        '',
        'Generated by static repository audit tooling. This report does not prove runtime safety.',
        '',
        "## Scope",
        '',
        $Scope,
        '',
        "## Summary",
        '',
        "- Finding count: $(@($Findings).Count)",
        "- Severity counts: $counts",
        "- Runtime FXServer validation: not executed in this pass.",
        "- MariaDB migration execution: not executed in this pass."
    ) + $Extra + @(
        '',
        '## Findings',
        '',
        (Finding-Table $Findings)
    )
    Set-Content -LiteralPath (Join-Path $root $Path) -Value ($content -join "`n") -Encoding UTF8
}

$all = Read-AuditJson 'all'
$suiteData = @{
    syntax = Read-AuditJson 'syntax'
    manifests = Read-AuditJson 'manifests'
    exports = Read-AuditJson 'exports'
    events = Read-AuditJson 'events'
    clientTrust = Read-AuditJson 'client-trust'
    permissions = Read-AuditJson 'permissions'
    dupe = Read-AuditJson 'dupe'
    sql = Read-AuditJson 'sql'
    nui = Read-AuditJson 'nui'
    network = Read-AuditJson 'network'
    secrets = Read-AuditJson 'secrets'
    restart = Read-AuditJson 'restart'
}

$files = Get-RepoFiles
$manifestFiles = @($files | Where-Object { (Split-Path -Leaf $_) -eq 'fxmanifest.lua' })
$resources = @($manifestFiles | ForEach-Object { Split-Path -Leaf (Split-Path -Parent $_) })
$extensionCounts = $files | ForEach-Object { [System.IO.Path]::GetExtension($_).ToLowerInvariant() } | Group-Object | Sort-Object Name
$luaFiles = @($files | Where-Object { $_ -like '*.lua' })
$jsTsFiles = @($files | Where-Object { $_ -match '\.(js|jsx|ts|tsx)$' })
$nuiFiles = @($files | Where-Object { $_ -match '\\web\\|/web/|html|css|\.js$' })
$sqlFiles = @($files | Where-Object { $_ -like '*.sql' -or $_ -match 'migration|database' })
$validators = @($files | Where-Object { $_.Replace('\', '/') -match '^scripts/validate-.*\.ps1$' })

$inventoryLines = New-Object System.Collections.Generic.List[string]
$inventoryLines.Add('# Full Repository File Inventory') | Out-Null
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('- Repository path: `' + $root + '`') | Out-Null
$inventoryLines.Add('- Total included files: ' + $files.Count) | Out-Null
$inventoryLines.Add('- Ignored file count from last audit run: ' + @($all.skipped).Count) | Out-Null
$inventoryLines.Add('- Resource count: ' + $resources.Count) | Out-Null
$inventoryLines.Add('- Manifest count: ' + $manifestFiles.Count) | Out-Null
$inventoryLines.Add('- Lua files: ' + $luaFiles.Count) | Out-Null
$inventoryLines.Add('- JS/TS files: ' + $jsTsFiles.Count) | Out-Null
$inventoryLines.Add('- NUI-related files: ' + $nuiFiles.Count) | Out-Null
$inventoryLines.Add('- SQL/database/migration-related files: ' + $sqlFiles.Count) | Out-Null
$inventoryLines.Add('- Validator scripts: ' + $validators.Count) | Out-Null
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('## Ignored Categories') | Out-Null
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('- `.git`: repository internals and Codex checkpoints, not source.') | Out-Null
$inventoryLines.Add('- `node_modules`: external vendor dependencies.') | Out-Null
$inventoryLines.Add('- `dist`, `build`, `.next`, `coverage`: generated build/test artifacts.') | Out-Null
$inventoryLines.Add('- `vendor`: external bundled code.') | Out-Null
$inventoryLines.Add('- `.agents`, `.codex`: local automation/session artifacts.') | Out-Null
$inventoryLines.Add('- Unsupported binary extensions: counted as skipped when encountered.') | Out-Null
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('## File Counts By Extension') | Out-Null
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('| Extension | Count |') | Out-Null
$inventoryLines.Add('| --- | ---: |') | Out-Null
foreach ($group in $extensionCounts) {
    $name = if ($group.Name -eq '') { '[none]' } else { $group.Name }
    $inventoryLines.Add('| ' + $name + ' | ' + $group.Count + ' |') | Out-Null
}
$inventoryLines.Add('') | Out-Null
$inventoryLines.Add('## Resources') | Out-Null
$inventoryLines.Add('') | Out-Null
foreach ($resourceName in ($resources | Sort-Object)) {
    $inventoryLines.Add('- ' + $resourceName) | Out-Null
}
Set-Content -LiteralPath (Join-Path $root 'docs/security/full-repository-file-inventory.md') -Value ($inventoryLines -join "`n") -Encoding UTF8

$graph = @()
$resourceRows = @('| Resource | Dependencies | Exports | Network Events | NUI | DB Access | Findings |', '| --- | --- | --- | ---: | --- | --- | ---: |')
foreach ($manifest in $manifestFiles) {
    $manifestPath = Join-Path $root $manifest
    $resource = Split-Path -Leaf (Split-Path -Parent $manifest)
    $dir = Split-Path -Parent $manifest
    $content = Get-Content -LiteralPath $manifestPath -Raw
    $deps = New-Object System.Collections.Generic.List[string]
    foreach ($m in [regex]::Matches($content, 'dependency\s+[\x27\x22]([^\x27\x22]+)[\x27\x22]|dependencies\s*\{(?<block>[\s\S]*?)\}')) {
        if ($m.Groups[1].Success) { $deps.Add($m.Groups[1].Value) | Out-Null }
        if ($m.Groups['block'].Success) {
            foreach ($inner in [regex]::Matches($m.Groups['block'].Value, '[\x27\x22]([^\x27\x22]+)[\x27\x22]')) { $deps.Add($inner.Groups[1].Value) | Out-Null }
        }
    }
    $resourceFiles = @($files | Where-Object { $_.StartsWith($dir.Replace('\', '/') + '/') })
    $exports = @()
    $events = 0
    $db = $false
    foreach ($rf in $resourceFiles | Where-Object { $_ -like '*.lua' }) {
        $text = Get-Content -LiteralPath (Join-Path $root $rf) -Raw
        $events += ([regex]::Matches($text, 'RegisterNetEvent|RegisterNUICallback')).Count
        if ($text -match 'MySQL\.|oxmysql|Database\.|GetCoreObject\(\).*Database') { $db = $true }
        foreach ($m in [regex]::Matches($text, 'exports\s*\(\s*[\x27\x22]([^\x27\x22]+)[\x27\x22]')) { $exports += $m.Groups[1].Value }
    }
    $hasNui = $content -match 'ui_page'
    $findingCount = @($all.findings | Where-Object { $_.Path -like "$dir/*" -or $_.Path -like "$resource/*" }).Count
    $resourceRows += '| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f (Escape-Cell $resource), (Escape-Cell (($deps | Select-Object -Unique) -join ', ')), (Escape-Cell (($exports | Select-Object -Unique) -join ', ')), $events, $hasNui, $db, $findingCount
    $graph += [pscustomobject]@{ resource = $resource; manifest = $manifest; dependencies = @($deps | Select-Object -Unique); nui = $hasNui; database_access = $db }
}
($graph | ConvertTo-Json -Depth 5) | Set-Content -LiteralPath (Join-Path $root 'docs/security/full-dependency-graph.json') -Encoding UTF8

Write-Report 'docs/security/full-resource-audit.md' 'Full Resource Audit' 'Every `fxmanifest.lua` resource discovered by `rg --files` was inspected for manifest fields, dependency declarations, exports, NUI markers, events and database access.' $suiteData.manifests.findings @('', '## Resource Table', '', ($resourceRows -join "`n"))
Write-Report 'docs/security/full-syntax-parse-report.md' 'Full Syntax and Parse Report' 'JSON, JavaScript, PowerShell, XML and Lua files were checked where local parsers were available. Lua parser was unavailable and is explicitly listed as an open limitation.' $suiteData.syntax.findings
Write-Report 'docs/security/full-dependency-audit.md' 'Full Dependency Audit' 'Resource dependencies were extracted from manifests. A machine-readable graph is stored in `docs/security/full-dependency-graph.json`.' $suiteData.manifests.findings
Write-Report 'docs/security/full-export-audit.md' 'Full Export Audit' 'Lua export declarations and cross-resource export calls were statically matched. Static matching can miss dynamic or manifest-only exports and can produce review findings.' $suiteData.exports.findings
Write-Report 'docs/security/full-event-callback-audit.md' 'Full Event and Callback Audit' 'Network events, NUI callbacks, server/client triggers and callback boundaries were scanned for nearby validation, actor, permission and rate-limit markers.' $suiteData.events.findings
Write-Report 'docs/security/client-trust-audit.md' 'Client Trust Audit' 'Server-side consumption of sensitive payload fields was scanned for nearby validation and authority markers.' $suiteData.clientTrust.findings
Write-Report 'docs/security/permission-admin-audit.md' 'Permission and Admin Security Audit' 'Permission checks, unrestricted commands, ACE usage and hardcoded privileged identifiers were scanned.' $suiteData.permissions.findings
Write-Report 'docs/security/inventory-item-dupe-audit.md' 'Inventory and Item Dupe Audit' 'Inventory, item, shop, crafting and storage operations were scanned for atomicity, idempotency and locking markers.' @($suiteData.dupe.findings | Where-Object { $_.Path -match 'inventory|items|shop|craft|storage|evidence' })
Write-Report 'docs/security/economy-money-dupe-audit.md' 'Economy and Money Dupe Audit' 'Banking, economy, payroll, billing, shop and transaction paths were scanned for ledger/transaction/idempotency markers.' @($suiteData.dupe.findings + $suiteData.sql.findings | Where-Object { $_.Path -match 'bank|economy|payroll|billing|shop|money|launder|invoice' })
Write-Report 'docs/security/vehicle-dupe-security-audit.md' 'Vehicle Security and Dupe Audit' 'Vehicle, garage, fuel, impound, key and dealer paths were scanned for ownership, atomicity and restart-risk markers.' @($suiteData.dupe.findings + $suiteData.restart.findings | Where-Object { $_.Path -match 'vehicle|garage|fuel|impound|dealer|keys' })
Write-Report 'docs/security/property-security-dupe-audit.md' 'Property Security and Dupe Audit' 'Property, housing, furniture, lease, key, storage and security paths were scanned for ownership and restart-risk markers.' @($suiteData.dupe.findings + $suiteData.restart.findings | Where-Object { $_.Path -match 'property|housing|furniture|lease|resident|door' })
Write-Report 'docs/security/gameplay-domain-security-audit.md' 'Gameplay Domain Security Audit' 'Jobs, shops, crafting, crime, drugs, robberies, blackmarket and laundering paths were scanned for client-success, replay and reward-risk markers.' @($suiteData.dupe.findings + $suiteData.events.findings | Where-Object { $_.Path -match 'job|shop|craft|crime|drug|robber|blackmarket|moneywash|chopshop|illegal' })
Write-Report 'docs/security/database-migration-audit.md' 'Database and Migration Audit' 'SQL, database modules and migration-like files were scanned for direct driver calls, dynamic SQL, destructive SQL and transaction-risk markers.' $suiteData.sql.findings
Write-Report 'docs/security/nui-frontend-security-audit.md' 'NUI and Frontend Security Audit' 'NUI JavaScript and HTML were scanned for unsafe HTML sinks, dynamic code, remote scripts and message handler validation issues.' $suiteData.nui.findings
Write-Report 'docs/security/network-file-security-audit.md' 'Network, File and SSRF Security Audit' 'HTTP references, NUI fetches, resource file primitives and path traversal markers were scanned.' $suiteData.network.findings
Write-Report 'docs/security/secrets-backdoor-audit.md' 'Secrets and Backdoor Audit' 'Credential-like strings, webhooks, private keys, JWT-like tokens and dynamic loading primitives were scanned. Values are masked/truncated.' $suiteData.secrets.findings
Write-Report 'docs/security/performance-stability-audit.md' 'Performance and Stability Audit' 'Restart cleanup, polling, runtime state primitives and broad network/file patterns were used as performance and stability review signals.' @($suiteData.restart.findings + $suiteData.network.findings | Where-Object { $_.Rule -match 'restart|disconnect|network|file' })
Write-Report 'docs/security/resource-restart-cleanup-audit.md' 'Resource Restart and Cleanup Audit' 'Resources using runtime state primitives were checked for `onResourceStop` and disconnect cleanup markers.' $suiteData.restart.findings
Write-Report 'docs/security/open-runtime-security-tests.md' 'Open Runtime Security Tests' 'Live FXServer, MariaDB migration execution and runtime harness suites were not executed in this static pass.' @() @('', '## Open Tests', '', '- FXServer full start/stop/restart with complete server.cfg.', '- MariaDB empty-schema migration execution and idempotency rerun.', '- Runtime harnesses with isolated fixtures.', '- NUI browser interaction/security review in a running client.', '- Economy, inventory, vehicle and property replay tests under concurrency.')

$allFindings = @($all.findings)
$severityCounts = $allFindings | Group-Object Severity | ForEach-Object { "- $($_.Name): $($_.Count)" }
$finalRating = 'NICHT ALPHA-REIF'
$validatorSummaryPath = Join-Path $root 'docs\security\full-validator-run-summary.json'
$validatorSummary = if (Test-Path -LiteralPath $validatorSummaryPath) { Get-Content -LiteralPath $validatorSummaryPath -Raw | ConvertFrom-Json } else { $null }
$validatorTotalLine = if ($validatorSummary) { "- Total validators executed: $($validatorSummary.total)" } else { '- Total validators executed: not run after report generation' }
$validatorPassedLine = if ($validatorSummary) { "- Passed validators: $($validatorSummary.passed)" } else { '- Passed validators: not available' }
$validatorFailedLine = if ($validatorSummary) { "- Failed validators: $($validatorSummary.failed)" } else { '- Failed validators: not available' }
$mainExtra = @(
    '',
    '## Inventory Snapshot',
    '',
    "- Total included files: $($files.Count)",
    "- Resources: $($resources.Count)",
    "- Lua files: $($luaFiles.Count)",
    "- JS/TS files: $($jsTsFiles.Count)",
    "- NUI-related files: $($nuiFiles.Count)",
    "- SQL/database/migration-related files: $($sqlFiles.Count)",
    "- Validator scripts: $($validators.Count)",
    '',
    '## Validator Run',
    '',
    $validatorTotalLine,
    $validatorPassedLine,
    $validatorFailedLine,
    '',
    '## Severity Counts',
    '',
    ($severityCounts -join "`n"),
    '',
    '## Final Static Risk Rating',
    '',
    "**$finalRating**",
    '',
    'Reason: static audit found open HIGH findings and no live FXServer or MariaDB migration test was executed.'
)
Write-Report 'docs/security/full-repository-security-report.md' 'Full Repository Security Report' 'Complete recursive static audit across resources, manifests, Lua, NUI, scripts, docs with executable examples, SQL/database modules and validators. Generated artifacts and vendor/build directories were excluded and documented in the inventory.' $allFindings $mainExtra

Write-Host 'Security audit reports written.'
