NexaPoliceDatabase = {}

local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_POLICE_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'police.db' }) end

function NexaPoliceDatabase.Migrate()
    local db = coreDatabase()
    if not db or not db.RegisterMigration then return false, 'Core database unavailable.' end
    db.RegisterMigration({
        id = '161_police_foundation',
        description = 'Create police agencies arrests restraints searches seizures and checks.',
        transaction = false,
        up = function()
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_agencies (id INT AUTO_INCREMENT PRIMARY KEY, agency_key VARCHAR(64) UNIQUE NOT NULL, label VARCHAR(128) NOT NULL, agency_type VARCHAR(32) NOT NULL, organization_id INT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.agencies' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_arrests (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, agency_key VARCHAR(64) NULL, reason VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.arrests' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_restraints (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, restraint_type VARCHAR(32) NOT NULL, enabled TINYINT(1) NOT NULL, reason VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.restraints' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_searches (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, search_type VARCHAR(32) NOT NULL, reason VARCHAR(255) NOT NULL, result LONGTEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.searches' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_seizures (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NULL, officer_character_id BIGINT NULL, item_reference VARCHAR(128) NULL, reason VARCHAR(255) NOT NULL, evidence_id INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.seizures' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_fines (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, amount INT NOT NULL, reason VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'issued', billing_reference VARCHAR(128) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.fines' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_bookings (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, arrest_id INT NULL, report_id INT NULL, evidence_id INT NULL, reason VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, finalized_at TIMESTAMP NULL, revision INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.bookings' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_incarcerations (id INT AUTO_INCREMENT PRIMARY KEY, booking_id INT NULL, subject_character_id BIGINT NOT NULL, started_by BIGINT NULL, released_by BIGINT NULL, sentence_minutes INT NOT NULL, status VARCHAR(32) NOT NULL, starts_at TIMESTAMP NULL, release_at TIMESTAMP NULL, released_at TIMESTAMP NULL, release_reason VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.incarcerations' })
            db.Query([[CREATE TABLE IF NOT EXISTS nexa_police_transports (id INT AUTO_INCREMENT PRIMARY KEY, subject_character_id BIGINT NOT NULL, officer_character_id BIGINT NULL, vehicle_reference VARCHAR(128) NULL, transport_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'police.migration.transports' })
            db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_police_bookings_subject ON nexa_police_bookings (subject_character_id, status)]], {}, { category = 'police.migration.index.bookings_subject' })
            db.Query([[CREATE INDEX IF NOT EXISTS idx_nexa_police_jail_subject ON nexa_police_incarcerations (subject_character_id, status)]], {}, { category = 'police.migration.index.jail_subject' })
            return true
        end
    })
    return db.RunMigrations()
end

function NexaPoliceDatabase.InsertAgency(a) return dbCall('Insert', 'INSERT INTO nexa_police_agencies (agency_key, label, agency_type, organization_id, enabled, metadata) VALUES (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE label = VALUES(label), agency_type = VALUES(agency_type), organization_id = VALUES(organization_id), enabled = VALUES(enabled), metadata = VALUES(metadata)', { a.agency_key, a.label, a.agency_type, a.organization_id, a.enabled and 1 or 0, encode(a.metadata) }, 'police.agency.upsert') end
function NexaPoliceDatabase.GetAgency(key) return dbCall('Single', 'SELECT * FROM nexa_police_agencies WHERE agency_key = ? LIMIT 1', { key }, 'police.agency.get') end
function NexaPoliceDatabase.ListAgencies() return dbCall('Query', 'SELECT * FROM nexa_police_agencies ORDER BY agency_key ASC', {}, 'police.agency.list') end
function NexaPoliceDatabase.InsertArrest(a) return dbCall('Insert', 'INSERT INTO nexa_police_arrests (subject_character_id, officer_character_id, agency_key, reason, status, metadata) VALUES (?, ?, ?, ?, ?, ?)', { a.subject_character_id, a.officer_character_id, a.agency_key, a.reason, a.status, encode(a.metadata) }, 'police.arrest.insert') end
function NexaPoliceDatabase.InsertRestraint(r) return dbCall('Insert', 'INSERT INTO nexa_police_restraints (subject_character_id, officer_character_id, restraint_type, enabled, reason, metadata) VALUES (?, ?, ?, ?, ?, ?)', { r.subject_character_id, r.officer_character_id, r.restraint_type, r.enabled and 1 or 0, r.reason, encode(r.metadata) }, 'police.restraint.insert') end
function NexaPoliceDatabase.InsertSearch(s) return dbCall('Insert', 'INSERT INTO nexa_police_searches (subject_character_id, officer_character_id, search_type, reason, result, metadata) VALUES (?, ?, ?, ?, ?, ?)', { s.subject_character_id, s.officer_character_id, s.search_type, s.reason, encode(s.result), encode(s.metadata) }, 'police.search.insert') end
function NexaPoliceDatabase.InsertSeizure(s) return dbCall('Insert', 'INSERT INTO nexa_police_seizures (subject_character_id, officer_character_id, item_reference, reason, evidence_id, metadata) VALUES (?, ?, ?, ?, ?, ?)', { s.subject_character_id, s.officer_character_id, s.item_reference, s.reason, s.evidence_id, encode(s.metadata) }, 'police.seizure.insert') end
function NexaPoliceDatabase.InsertFine(f) return dbCall('Insert', 'INSERT INTO nexa_police_fines (subject_character_id, officer_character_id, amount, reason, status, billing_reference, metadata) VALUES (?, ?, ?, ?, ?, ?, ?)', { f.subject_character_id, f.officer_character_id, f.amount, f.reason, f.status, f.billing_reference, encode(f.metadata) }, 'police.fine.insert') end
function NexaPoliceDatabase.InsertBooking(b) return dbCall('Insert', 'INSERT INTO nexa_police_bookings (subject_character_id, officer_character_id, arrest_id, report_id, evidence_id, reason, status, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', { b.subject_character_id, b.officer_character_id, b.arrest_id, b.report_id, b.evidence_id, b.reason, b.status, encode(b.metadata) }, 'police.booking.insert') end
function NexaPoliceDatabase.GetBooking(id) return dbCall('Single', 'SELECT * FROM nexa_police_bookings WHERE id = ? LIMIT 1', { id }, 'police.booking.get') end
function NexaPoliceDatabase.SetBookingStatus(id, status) return dbCall('Update', 'UPDATE nexa_police_bookings SET status = ?, finalized_at = CASE WHEN ? = ? THEN CURRENT_TIMESTAMP ELSE finalized_at END, revision = revision + 1 WHERE id = ? AND status = ?', { status, status, NEXA_BOOKING_STATUS.finalized, id, NEXA_BOOKING_STATUS.draft }, 'police.booking.status') end
function NexaPoliceDatabase.InsertIncarceration(j) return dbCall('Insert', 'INSERT INTO nexa_police_incarcerations (booking_id, subject_character_id, started_by, sentence_minutes, status, starts_at, release_at, metadata) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL ? MINUTE), ?)', { j.booking_id, j.subject_character_id, j.started_by, j.sentence_minutes, j.status, j.sentence_minutes, encode(j.metadata) }, 'police.jail.insert') end
function NexaPoliceDatabase.GetIncarceration(id) return dbCall('Single', 'SELECT * FROM nexa_police_incarcerations WHERE id = ? LIMIT 1', { id }, 'police.jail.get') end
function NexaPoliceDatabase.ReleaseIncarceration(id, actor, reason, status) return dbCall('Update', 'UPDATE nexa_police_incarcerations SET status = ?, released_by = ?, released_at = CURRENT_TIMESTAMP, release_reason = ? WHERE id = ? AND status = ?', { status or NEXA_INCARCERATION_STATUS.released, actor, reason, id, NEXA_INCARCERATION_STATUS.active }, 'police.jail.release') end
function NexaPoliceDatabase.InsertTransport(t) return dbCall('Insert', 'INSERT INTO nexa_police_transports (subject_character_id, officer_character_id, vehicle_reference, transport_type, status, metadata) VALUES (?, ?, ?, ?, ?, ?)', { t.subject_character_id, t.officer_character_id, t.vehicle_reference, t.transport_type, t.status, encode(t.metadata) }, 'police.transport.insert') end
function NexaPoliceDatabase.GetSchema() return { migration = '161_police_foundation', tables = { 'nexa_police_agencies', 'nexa_police_arrests', 'nexa_police_restraints', 'nexa_police_searches', 'nexa_police_seizures', 'nexa_police_fines', 'nexa_police_bookings', 'nexa_police_incarcerations', 'nexa_police_transports' } } end
