NexaEvidenceDatabase = {}
local function coreDatabase() if GetResourceState('nexa-core') ~= 'started' then return nil end; local ok, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return ok and core and core.Database or nil end
local function encode(value) local ok, encoded = pcall(json.encode, value or {}); return ok and encoded or '{}' end
local function dbCall(method, sql, params, category) local db = coreDatabase(); if not db or not db[method] then return nil, { code = NEXA_EVIDENCE_ERRORS.databaseError } end; return db[method](sql, params or {}, { category = category or 'evidence.db' }) end
function NexaEvidenceDatabase.Migrate() local db = coreDatabase(); if not db or not db.RegisterMigration then return false end; db.RegisterMigration({ id = '164_evidence_foundation', description = 'Create evidence records traces locker and chain custody.', transaction = false, up = function() db.Query([[CREATE TABLE IF NOT EXISTS nexa_evidence_records (id INT AUTO_INCREMENT PRIMARY KEY, evidence_type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, collected_by BIGINT NULL, location_json LONGTEXT NULL, reference_json LONGTEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'evidence.migration.records' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_evidence_traces (id INT AUTO_INCREMENT PRIMARY KEY, trace_type VARCHAR(32) NOT NULL, source_reference VARCHAR(128) NULL, evidence_id INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'evidence.migration.traces' }); db.Query([[CREATE TABLE IF NOT EXISTS nexa_evidence_locker (id INT AUTO_INCREMENT PRIMARY KEY, evidence_id INT NOT NULL, locker_key VARCHAR(64) NOT NULL, stored_by BIGINT NULL, stored_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, metadata LONGTEXT NULL)]], {}, { category = 'evidence.migration.locker' }); return true end }); return db.RunMigrations() end
function NexaEvidenceDatabase.InsertEvidence(e) return dbCall('Insert', 'INSERT INTO nexa_evidence_records (evidence_type, status, collected_by, location_json, reference_json, metadata) VALUES (?, ?, ?, ?, ?, ?)', { e.evidence_type, e.status, e.collected_by, encode(e.location), encode(e.reference), encode(e.metadata) }, 'evidence.record.insert') end
function NexaEvidenceDatabase.ListEvidence(filters) return dbCall('Query', 'SELECT * FROM nexa_evidence_records ORDER BY id DESC LIMIT 500', {}, 'evidence.record.list') end
function NexaEvidenceDatabase.UpdateStatus(id, status) return dbCall('Update', 'UPDATE nexa_evidence_records SET status = ? WHERE id = ?', { status, id }, 'evidence.record.status') end
function NexaEvidenceDatabase.InsertTrace(t) return dbCall('Insert', 'INSERT INTO nexa_evidence_traces (trace_type, source_reference, evidence_id, metadata) VALUES (?, ?, ?, ?)', { t.trace_type, t.source_reference, t.evidence_id, encode(t.metadata) }, 'evidence.trace.insert') end
function NexaEvidenceDatabase.StoreLocker(l) return dbCall('Insert', 'INSERT INTO nexa_evidence_locker (evidence_id, locker_key, stored_by, metadata) VALUES (?, ?, ?, ?)', { l.evidence_id, l.locker_key, l.stored_by, encode(l.metadata) }, 'evidence.locker.store') end
function NexaEvidenceDatabase.GetSchema() return { migration = '164_evidence_foundation', tables = { 'nexa_evidence_records', 'nexa_evidence_traces', 'nexa_evidence_locker' } } end
