local migrated = false
local hooks = {}
local function response(success, code, message, data, meta) return { ok = success == true, success = success == true, code = code or (success and 'OK' or NEXA_EVIDENCE_ERRORS.invalidInput), message = message or '', data = data, meta = meta, error = success == true and nil or { code = code, message = message } } end
local function ok(data, message, meta) return response(true, 'OK', message or 'OK', data, meta) end
local function fail(code, message, meta) return response(false, code, message or code, nil, meta) end
local function encode(value) local good, encoded = pcall(json.encode, value or {}); return good and encoded or '{}' end
local function getCore() if GetResourceState('nexa-core') ~= 'started' then return nil end; local good, core = pcall(function() return exports['nexa-core']:GetCoreObject() end); return good and core or nil end
local function log(level, category, message, context) local core = getCore(); if core and core.Logger and core.Logger[level] then core.Logger[level](category, message, context); return end; print(('[%s] [%s] %s %s'):format(NEXA_EVIDENCE.resourceName, level, message, encode(context))) end
local function emit(eventName, payload) local core = getCore(); if core and core.EventBus then core.EventBus.Emit(eventName, payload, { resource = NEXA_EVIDENCE.resourceName }) end end
local function registerCallback(name, handler) if GetResourceState('nexa_api') == 'started' then exports.nexa_api:RegisterServerCallback(name, handler) end end
function RegisterEvidenceType(definition) definition = type(definition) == 'table' and definition or {}; if type(definition.evidence_type) ~= 'string' or definition.evidence_type == '' then return fail(NEXA_EVIDENCE_ERRORS.typeInvalid, 'Evidence type is invalid.') end; local id, err = NexaEvidenceDatabase.UpsertType({ evidence_type = definition.evidence_type, label = definition.label or definition.evidence_type, enabled = definition.enabled ~= false, metadata = definition.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence type could not be registered.', err) end; emit(NEXA_EVIDENCE_EVENTS.typeRegistered, { evidence_type = definition.evidence_type }); return ok({ evidence_type_id = id, evidence_type = definition.evidence_type }, 'Evidence type registered.') end
function CollectEvidence(payload) payload = type(payload) == 'table' and payload or {}; if not NEXA_EVIDENCE_TYPES[payload.evidence_type or 'custom'] then return fail(NEXA_EVIDENCE_ERRORS.typeInvalid, 'Evidence type is invalid.') end; local id, err = NexaEvidenceDatabase.InsertEvidence({ evidence_type = payload.evidence_type or 'custom', status = payload.status or NEXA_EVIDENCE_STATUS.collected, collected_by = tonumber(payload.collected_by), location = payload.location or {}, reference = payload.reference or {}, metadata = payload.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence could not be collected.', err) end; NexaEvidenceDatabase.InsertCustody({ evidence_id = id, action = 'collected', actor_character_id = tonumber(payload.collected_by), to_location = payload.location_key, metadata = payload.metadata or {} }); emit(NEXA_EVIDENCE_EVENTS.collected, { evidence_id = id }); return ok({ evidence_id = id }, 'Evidence collected.') end
function ListEvidence(filters) local rows, err = NexaEvidenceDatabase.ListEvidence(filters); return err and fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence could not be listed.', err) or ok(rows or {}, 'Evidence listed.') end
function UpdateEvidenceStatus(evidenceId, status, payload) if not NEXA_EVIDENCE_STATUS[status] then return fail(NEXA_EVIDENCE_ERRORS.statusInvalid, 'Evidence status is invalid.') end; payload = type(payload) == 'table' and payload or {}; NexaEvidenceDatabase.UpdateStatus(tonumber(evidenceId), status); NexaEvidenceDatabase.InsertCustody({ evidence_id = tonumber(evidenceId), action = 'status:' .. status, actor_character_id = tonumber(payload.actor_character_id), metadata = payload.metadata or {} }); emit(NEXA_EVIDENCE_EVENTS.statusChanged, { evidence_id = evidenceId, status = status }); return ok({ evidence_id = evidenceId, status = status }, 'Evidence status updated.') end
function RegisterEvidenceHook(name, hook) if type(name) ~= 'string' or type(hook) ~= 'table' then return false end; hooks[name] = hook; return true end
function CreateTrace(traceType, sourceReference, payload) payload = type(payload) == 'table' and payload or {}; local id, err = NexaEvidenceDatabase.InsertTrace({ trace_type = traceType or 'custom', source_reference = sourceReference, evidence_id = tonumber(payload.evidence_id), metadata = payload.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Trace could not be created.', err) end; emit(NEXA_EVIDENCE_EVENTS.traceCreated, { trace_id = id, trace_type = traceType }); return ok({ trace_id = id }, 'Evidence trace created.') end
function PackageEvidence(evidenceId, payload) payload = type(payload) == 'table' and payload or {}; local packageKey = payload.package_key or ('EV-' .. tostring(evidenceId)); local updated, err = NexaEvidenceDatabase.PackageEvidence(tonumber(evidenceId), packageKey, payload.case_reference); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence could not be packaged.', err) end; NexaEvidenceDatabase.InsertCustody({ evidence_id = tonumber(evidenceId), action = 'packaged', actor_character_id = tonumber(payload.actor_character_id), to_location = packageKey, metadata = payload.metadata or {} }); emit(NEXA_EVIDENCE_EVENTS.packaged, { evidence_id = evidenceId, package_key = packageKey }); return ok({ evidence_id = evidenceId, package_key = packageKey, updated = updated }, 'Evidence packaged.') end
function RecordCustody(evidenceId, action, payload) payload = type(payload) == 'table' and payload or {}; local id, err = NexaEvidenceDatabase.InsertCustody({ evidence_id = tonumber(evidenceId), action = action or 'transfer', actor_character_id = tonumber(payload.actor_character_id), from_location = payload.from_location, to_location = payload.to_location, metadata = payload.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Custody entry could not be recorded.', err) end; emit(NEXA_EVIDENCE_EVENTS.custodyRecorded, { custody_id = id, evidence_id = evidenceId }); return ok({ custody_id = id }, 'Custody recorded.') end
function RequestAnalysis(evidenceId, analysisType, payload) payload = type(payload) == 'table' and payload or {}; local id, err = NexaEvidenceDatabase.InsertAnalysis({ evidence_id = tonumber(evidenceId), analysis_type = analysisType or 'general', status = 'pending', requested_by = tonumber(payload.requested_by), result = {}, metadata = payload.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence analysis could not be requested.', err) end; NexaEvidenceDatabase.UpdateStatus(tonumber(evidenceId), NEXA_EVIDENCE_STATUS.in_analysis); emit(NEXA_EVIDENCE_EVENTS.analysisStarted, { analysis_id = id, evidence_id = evidenceId }); return ok({ analysis_id = id }, 'Evidence analysis requested.') end
function CompleteAnalysis(analysisId, payload) payload = type(payload) == 'table' and payload or {}; local updated, err = NexaEvidenceDatabase.CompleteAnalysis(tonumber(analysisId), tonumber(payload.completed_by), payload.result or {}); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence analysis could not be completed.', err) end; emit(NEXA_EVIDENCE_EVENTS.analysisCompleted, { analysis_id = analysisId }); return ok({ analysis_id = analysisId, updated = updated }, 'Evidence analysis completed.') end
function StoreEvidenceLocker(evidenceId, lockerKey, payload) payload = type(payload) == 'table' and payload or {}; local id, err = NexaEvidenceDatabase.StoreLocker({ evidence_id = tonumber(evidenceId), locker_key = lockerKey or 'default', stored_by = tonumber(payload.stored_by), metadata = payload.metadata or {} }); if err then return fail(NEXA_EVIDENCE_ERRORS.databaseError, 'Evidence could not be stored.', err) end; UpdateEvidenceStatus(evidenceId, NEXA_EVIDENCE_STATUS.stored, { actor_character_id = payload.stored_by, metadata = { locker_key = lockerKey } }); emit(NEXA_EVIDENCE_EVENTS.lockerStored, { locker_record_id = id, evidence_id = evidenceId }); return ok({ locker_record_id = id }, 'Evidence stored in locker.') end
local function registerCallbacks()
    registerCallback('nexa:evidence:cb:registerType', function(_, payload) return RegisterEvidenceType(payload) end)
    registerCallback('nexa:evidence:cb:collect', function(_, payload) return CollectEvidence(payload) end)
    registerCallback('nexa:evidence:cb:list', function(_, payload) return ListEvidence(payload) end)
    registerCallback('nexa:evidence:cb:package', function(_, payload) payload = type(payload) == 'table' and payload or {}; return PackageEvidence(payload.evidence_id, payload) end)
    registerCallback('nexa:evidence:cb:recordCustody', function(_, payload) payload = type(payload) == 'table' and payload or {}; return RecordCustody(payload.evidence_id, payload.action, payload) end)
    registerCallback('nexa:evidence:cb:requestAnalysis', function(_, payload) payload = type(payload) == 'table' and payload or {}; return RequestAnalysis(payload.evidence_id, payload.analysis_type, payload) end)
    registerCallback('nexa:evidence:cb:completeAnalysis', function(_, payload) payload = type(payload) == 'table' and payload or {}; return CompleteAnalysis(payload.analysis_id, payload) end)
end
AddEventHandler('onResourceStart', function(resourceName) if resourceName ~= GetCurrentResourceName() then return end; if NexaEvidenceConfig.autoMigrate then migrated = NexaEvidenceDatabase.Migrate() == true end; registerCallbacks(); log('Info', 'evidence.start', 'nexa_evidence started.', { migrated = migrated }) end)
exports('RegisterEvidenceType', RegisterEvidenceType)
exports('CollectEvidence', CollectEvidence)
exports('ListEvidence', ListEvidence)
exports('UpdateEvidenceStatus', UpdateEvidenceStatus)
exports('RegisterEvidenceHook', RegisterEvidenceHook)
exports('CreateTrace', CreateTrace)
exports('PackageEvidence', PackageEvidence)
exports('RecordCustody', RecordCustody)
exports('RequestAnalysis', RequestAnalysis)
exports('CompleteAnalysis', CompleteAnalysis)
exports('StoreEvidenceLocker', StoreEvidenceLocker)
exports('getStatus', function() return { resourceName = NEXA_EVIDENCE.resourceName, version = NEXA_EVIDENCE.version, migrated = migrated, hooks = hooks } end)
exports('getSchema', NexaEvidenceDatabase.GetSchema)
