NexaApiErrors = {
    OK = 'OK',
    CREATED = 'CREATED',
    UPDATED = 'UPDATED',
    NO_PERMISSION = 'NO_PERMISSION',
    NOT_FOUND = 'NOT_FOUND',
    INVALID_INPUT = 'INVALID_INPUT',
    RATE_LIMITED = 'RATE_LIMITED',
    CHARACTER_NOT_LOADED = 'CHARACTER_NOT_LOADED',
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
    INSUFFICIENT_ITEMS = 'INSUFFICIENT_ITEMS',
    DISTANCE_TOO_FAR = 'DISTANCE_TOO_FAR',
    RESOURCE_UNAVAILABLE = 'RESOURCE_UNAVAILABLE',
    CONFLICT = 'CONFLICT',
    SECURITY_REJECTED = 'SECURITY_REJECTED',
    DATABASE_ERROR = 'DATABASE_ERROR',
    INTERNAL_ERROR = 'INTERNAL_ERROR'
}
